const reportConfig = {
  candidates: {
    label: "Conference Registrations",

    fields: [
      {
        key: "name",
        label: "Name",
        mongo: "name",
        type: "text",
        filterable: true,
        exportable: true,
      },
      {
        key: "email",
        label: "Email",
        mongo: "email",
        type: "text",
        filterable: true,
        exportable: true,
      },
      {
        key: "mobile",
        label: "Mobile",
        mongo: "mobile",
        type: "text",
        filterable: true,
        exportable: true,
      },
      {
        key: "institution",
        label: "Institution",
        mongo: "institution",
        type: "text",
        filterable: true,
        exportable: true,
      },
      {
        key: "designation",
        label: "Designation",
        mongo: "designation",
        type: "text",
        filterable: true,
        exportable: true,
      },
      {
        key: "participationType",
        label: "Participation",
        mongo: "participationType",
        type: "select",
        options: ["Online", "Offline"],
        filterable: true,
        exportable: true,
      },
      {
        key: "certificateType",
        label: "Certificate Type",
        mongo: "certificateType",
        type: "select",
        options: [
          "Organizer",
          "Resource Person",
          "Delegate",
          "Research Paper",
          "Poster",
        ],
        filterable: true,
        exportable: true,
      },
      {
        key: "presentationTitle",
        label: "Paper / Poster Title",
        mongo: "presentationTitle",
        type: "text",
        filterable: true,
        exportable: true,
      },
      {
        key: "eventName",
        label: "Event",
        mongo: "eventName",
        type: "text",
        filterable: true,
        exportable: true,
      },
      {
        key: "status",
        label: "Status",
        mongo: "status",
        type: "select",
        options: ["Pending", "Approved", "Rejected"],
        filterable: true,
        exportable: true,
      },
      {
        key: "certificateId",
        label: "Certificate ID",
        mongo: "certificateId",
        type: "text",
        filterable: true,
        exportable: true,
      },
      {
        key: "createdAt",
        label: "Registration Date",
        mongo: "createdAt",
        type: "date",
        filterable: true,
        exportable: true,
      },
      {
        key: "approvedAt",
        label: "Approval Date",
        mongo: "approvedAt",
        type: "date",
        filterable: true,
        exportable: true,
      },
    ],

    defaultColumns: [
      "name",
      "email",
      "institution",
      "participationType",
      "certificateType",
      "status",
      "certificateId",
      "createdAt",
    ],

    previewLimit: 100,
  },
};

module.exports = reportConfig;